import Fluent

struct CreateFeedIngredient: AsyncMigration {
    func prepare(on database: Database) async throws {
        try await database.schema("feed_ingredients")
            .id()
            .field("code", .string, .required)
            .unique(on: "code")
            .field("name", .string, .required)
            .field("price_tl", .double)
            .field("is_available", .bool, .required, .sql(.default(true)))
            .field("source_file", .string, .required, .sql(.default("")))
            .field("version", .int, .required, .sql(.default(1)))
            .field("imported_at", .datetime)
            .field("updated_at", .datetime)
            .field("dry_matter", .double)
            .field("crude_protein", .double)
            .field("crude_ash", .double)
            .field("crude_fiber", .double)
            .field("crude_fat", .double)
            .field("starch", .double)
            .field("sugar", .double)
            .field("ndf", .double)
            .field("adf", .double)
            .field("adl", .double)
            .field("nfc", .double)
            .field("nsc", .double)
            .field("nfe", .double)
            .field("organic_matter", .double)
            .field("nel", .double)
            .field("me1x_n_r_c", .double)
            .field("tse9610", .double)
            .field("me_poultry_fixed", .double)
            .field("me_ruminant_fixed", .double)
            .field("ufl", .double)
            .field("ufv", .double)
            .field("neg_kazanc", .double)
            .field("maff_m_e", .double)
            .field("me_rum_alderman", .double)
            .field("me_rum_maff", .double)
            .field("me_poultry_c_c", .double)
            .field("me_poultry_e_c_n_f_e", .double)
            .field("me_poultry_e_c", .double)
            .field("me_poultry_cobb", .double)
            .field("pdie", .double)
            .field("pdia", .double)
            .field("pdin", .double)
            .field("rdp", .double)
            .field("rup", .double)
            .field("rup_c_p", .double)
            .field("frak_a", .double)
            .field("frak_b", .double)
            .field("frak_c", .double)
            .field("degradation_rate_b", .double)
            .field("sol_protein", .double)
            .field("ndcip", .double)
            .field("adicp", .double)
            .field("tdn", .double)
            .field("rds_starch", .double)
            .field("soluble_starch", .double)
            .field("slow_starch", .double)
            .field("sol_starch_pct", .double)
            .field("bypass_starch", .double)
            .field("calcium", .double)
            .field("phosphorus", .double)
            .field("total_phosphorus", .double)
            .field("avail_p", .double)
            .field("avail_p_chick", .double)
            .field("magnesium", .double)
            .field("potassium", .double)
            .field("sodium", .double)
            .field("chlorine", .double)
            .field("sulfur", .double)
            .field("ca_p", .double)
            .field("zinc", .double)
            .field("manganese", .double)
            .field("copper", .double)
            .field("cobalt", .double)
            .field("iron", .double)
            .field("selenium", .double)
            .field("iodine", .double)
            .field("methionine", .double)
            .field("lysine", .double)
            .field("met_cys", .double)
            .field("cystine", .double)
            .field("tryptophan", .double)
            .field("arginine", .double)
            .field("threonine", .double)
            .field("leucine", .double)
            .field("isoleucine", .double)
            .field("valine", .double)
            .field("phenylalanin", .double)
            .field("pheny_tyr", .double)
            .field("glycine", .double)
            .field("histidine", .double)
            .field("tyrosine", .double)
            .field("serine", .double)
            .field("proline", .double)
            .field("alanine", .double)
            .field("aspartic_acid", .double)
            .field("glutamic_acid", .double)
            .field("gly_ser", .double)
            .field("sin_methionine", .double)
            .field("sin_lysine", .double)
            .field("sin_met_cys", .double)
            .field("sin_cystine", .double)
            .field("sin_tryptophan", .double)
            .field("sin_arginine", .double)
            .field("sin_threonine", .double)
            .field("sin_leucine", .double)
            .field("sin_isoleucine", .double)
            .field("sin_valine", .double)
            .field("sin_phenylalanin", .double)
            .field("sin_histidine", .double)
            .field("linoleic_acid", .double)
            .field("linolenic_acid", .double)
            .field("arachidonic_acid", .double)
            .field("choline", .double)
            .field("lauric_acid", .double)
            .field("myristic_acid", .double)
            .field("palmitic_acid", .double)
            .field("palmoleic_acid", .double)
            .field("stearic_acid", .double)
            .field("oleic_acid", .double)
            .field("unsat_fatty_acid", .double)
            .field("sat_fatty_acid", .double)
            .field("free_fat", .double)
            .field("total_fatty_acid", .double)
            .field("met_lys", .double)
            .field("m_c_lys", .double)
            .field("arg_lys", .double)
            .field("thre_lys", .double)
            .field("leu_lys", .double)
            .field("val_lys", .double)
            .field("trp_lys", .double)
            .field("sin_meth_coeff", .double)
            .field("sin_lys_coeff", .double)
            .field("sin_cys_coeff", .double)
            .field("sin_arg_coeff", .double)
            .field("sin_thr_coeff", .double)
            .field("sin_leu_coeff", .double)
            .field("sin_iso_coeff", .double)
            .field("sin_val_coeff", .double)
            .field("sin_try_coeff", .double)
            .field("sin_phe_coeff", .double)
            .field("sin_his_coeff", .double)
            .field("alderman_coeff", .double)
            .field("maff_coeff", .double)
            .field("cc_coeff", .double)
            .field("ec_n_f_e_coeff", .double)
            .field("ec_coeff", .double)
            .field("cobb_coeff", .double)
            .field("dcap", .double)
            .field("pelet_renk", .double)
            .field("pelet_kalite", .double)
            .field("prest_kapasite", .double)
            .field("paf", .double)
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema("feed_ingredients").delete()
    }
}
